from __future__ import annotations


class TUIConstants:
    THEME_PAIR_IDS: dict[str, int] = {
        "selection": 1,
        "success": 2,
        "error": 3,
        "warning": 4,
        "accent": 5,
        "keyword": 6,
        "info": 7,
        "chrome": 8,
    }
    TABS = [
        "Overview",
        "Intercept",
        "Repeater",
        "Sitemap",
        "Match/Replace",
        "HTTP",
        "Export",
        "Settings",
        "Scope",
        "Filters",
        "Keybindings",
        "Rule Builder",
        "Theme Builder",
        "Findings",
        "Inspect",
    ]
    TAB_ACTIONS: dict[str, int] = {
        "open_overview": 0,
        "open_intercept": 1,
        "open_repeater": 2,
        "open_sitemap": 3,
        "open_match_replace": 4,
        "open_request": 5,
        "open_response": 5,
        "open_export": 6,
        "open_settings": 7,
        "open_keybindings": 10,
        "open_findings": 13,
        "open_inspect": 14,
    }
    DEFAULT_KEYBINDINGS: dict[str, str] = {
        "open_overview": "1",
        "open_intercept": "2",
        "open_repeater": "3",
        "open_sitemap": "4",
        "open_match_replace": "5",
        "open_request": "6",
        "open_response": "7",
        "open_export": "8",
        "open_settings": "w",
        "open_keybindings": "0",
        "open_findings": "9",
        "open_inspect": "I",
        "increase_http_horizontal_split": ">",
        "decrease_http_horizontal_split": "<",
        "increase_http_vertical_split": "}",
        "decrease_http_vertical_split": "{",
        "save_project": "s",
        "add_scope_host": "A",
        "load_repeater": "y",
        "edit_match_replace": "r",
        "toggle_body_view": "p",
        "toggle_word_wrap": "z",
        "toggle_scope_view": "o",
        "toggle_intercept_mode": "i",
        "forward_send": "a",
        "drop_item": "x",
        "edit_item": "e",
        "repeater_prev_session": "[",
        "repeater_next_session": "/",
        "open_expand": "R",
        "back": "B",
    }
    KEYBINDING_DESCRIPTIONS: dict[str, str] = {
        "open_overview": "Open the Overview workspace",
        "open_intercept": "Open the Intercept workspace",
        "open_repeater": "Open the Repeater workspace",
        "open_sitemap": "Open the Sitemap workspace",
        "open_match_replace": "Open the Match/Replace workspace",
        "open_request": "Open the HTTP workspace focused on Request",
        "open_response": "Open the HTTP workspace focused on Response",
        "open_export": "Open the Export workspace",
        "open_settings": "Open the Settings workspace",
        "open_keybindings": "Open the Keybindings workspace",
        "open_findings": "Open the Findings workspace",
        "open_inspect": "Open the Inspect workspace",
        "increase_http_horizontal_split": "Increase the primary pane width in multi-panel workspaces",
        "decrease_http_horizontal_split": "Decrease the primary pane width in multi-panel workspaces",
        "increase_http_vertical_split": "Give more height to the upper detail pane",
        "decrease_http_vertical_split": "Give more height to the lower detail pane",
        "save_project": "Save the current project",
        "add_scope_host": "Add the selected host to the scope allowlist",
        "load_repeater": "Load selected flow into Repeater",
        "edit_match_replace": "Edit Match/Replace rules",
        "toggle_body_view": "Toggle raw/pretty body mode",
        "toggle_word_wrap": "Toggle word wrap in text panes",
        "toggle_scope_view": "Toggle whether out-of-scope traffic is hidden from Flows and Sitemap",
        "toggle_intercept_mode": "Cycle interception mode",
        "forward_send": "Forward intercepted item or send Repeater request",
        "drop_item": "Drop intercepted item",
        "edit_item": "Edit intercepted item or Repeater request",
        "repeater_prev_session": "Go to previous Repeater session",
        "repeater_next_session": "Go to next Repeater session",
        "open_expand": "Open an expanded inspector view for the active request/response pane",
        "back": "Return to the previous workspace",
    }
    KEYBINDING_SECTIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
        (
            "Workspaces",
            (
                "open_overview",
                "open_intercept",
                "open_repeater",
                "open_sitemap",
                "open_match_replace",
                "open_request",
                "open_response",
                "open_export",
                "open_settings",
                "open_keybindings",
                "open_findings",
                "open_inspect",
            ),
        ),
        (
            "Layout",
            (
                "increase_http_horizontal_split",
                "decrease_http_horizontal_split",
                "increase_http_vertical_split",
                "decrease_http_vertical_split",
            ),
        ),
        (
            "Flow Actions",
            (
                "save_project",
                "add_scope_host",
                "load_repeater",
                "edit_match_replace",
                "toggle_body_view",
                "toggle_word_wrap",
                "toggle_scope_view",
                "toggle_intercept_mode",
                "open_expand",
            ),
        ),
        (
            "Editing And Send",
            (
                "forward_send",
                "drop_item",
                "edit_item",
            ),
        ),
        (
            "Repeater Sessions",
            (
                "repeater_prev_session",
                "repeater_next_session",
            ),
        ),
        (
            "Navigation",
            (
                "back",
            ),
        ),
    )
    LEGACY_KEYBINDING_ACTIONS: dict[str, str] = {
        "open_request_headers": "open_request",
        "open_request_body": "open_request",
        "open_response_headers": "open_response",
        "open_response_body": "open_response",
    }
